version: 3

tasks:
  build:

  imgui_test:
    deps:
      - build_imgui_test
    cmds:
      - bin/imgui_test
    method: none
    silent: true
  
  build_imgui_test:
    cmds:
      - odin build imgui_test/imgui_test.odin -file -out:bin/imgui_test.exe -o:speed -collection:dependencies=dependencies
    sources:
      - imgui_test/**/*.odin
      - dependencies/imgui/**/*.odin
    generates:
      - bin/imgui_test
    silent: true

  proto_main:
    deps:
      - build_proto_main
    cmds:
      - bin/proto_main
    method: none
    silent: true
  
  build_proto_main:
    cmds:
      - odin build proto_main/proto_main.odin -file -out:bin/proto_main.exe -o:speed -collection:dependencies=dependencies
    sources:
      - proto_main/**/*.odin
      - dependencies/imgui/**/*.odin
    generates:
      - bin/proto_main
    silent: true

interval: 100ms